//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace El_oasis_del_libro
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANTIDADVENDIDOS
    {
        public int IdCantidadVendido { get; set; }
        public int IdFactura { get; set; }
        public int IdLibro { get; set; }
        public int CantidadVendido { get; set; }
        public int TotalLibro { get; set; }
    
        public virtual LIBROS LIBROS { get; set; }
    }
}
