//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace El_oasis_del_libro
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIOS
    {
        public int IdInventario { get; set; }
        public int IdLibro { get; set; }
        public int CantidadInicial { get; set; }
        public Nullable<int> CantidadVendido { get; set; }
        public Nullable<int> CantidadActual { get; set; }
    
        public virtual LIBROS LIBROS { get; set; }
    }
}
