//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace El_oasis_del_libro
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        public int IdVenta { get; set; }
        public string IdCliente { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public int ValorTotal { get; set; }
        public int IdFactura { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
